name: clean_architecture_riverpod
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-64.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  ionicons: ^0.2.2

  # Networking
  retrofit: ^4.0.1
  dio: ^5.3.0

  # State Management
  # flutter_bloc: ^8.1.3
  provider: ^6.0.5

  # Others
  flutter_hooks: ^0.20.0
  get_it: ^7.6.0
  floor: ^1.4.2
  equatable: ^2.0.5
  oktoast: ^3.3.1
  awesome_dio_interceptor: ^1.0.0
  auto_route: ^7.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.1.2
  auto_route_generator: ^7.2.0
  retrofit_generator: ^7.0.8
  floor_generator: ^1.4.2
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
